// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDiKBElhuQ-eeko3IWjca7o_59n-44m2_g',
    appId: '1:260878765561:web:6d31a912f56ac46b904128',
    messagingSenderId: '260878765561',
    projectId: 'workermanager-803df',
    authDomain: 'workermanager-803df.firebaseapp.com',
    storageBucket: 'workermanager-803df.appspot.com',
    measurementId: 'G-7BYQD9D401',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDGlaP5hmoh4qj9xsbR5HtcybGBsErZaEk',
    appId: '1:260878765561:android:12431cdaa324eddb904128',
    messagingSenderId: '260878765561',
    projectId: 'workermanager-803df',
    storageBucket: 'workermanager-803df.appspot.com',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDiKBElhuQ-eeko3IWjca7o_59n-44m2_g',
    appId: '1:260878765561:web:4fa0407755c6dc73904128',
    messagingSenderId: '260878765561',
    projectId: 'workermanager-803df',
    authDomain: 'workermanager-803df.firebaseapp.com',
    storageBucket: 'workermanager-803df.appspot.com',
    measurementId: 'G-EWMKMN3LGM',
  );
}
