// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDyXN5mUa7mrOBW-BWpMXelc1RUT9hxSHw',
    appId: '1:856245188179:web:13d1bc5e539268838ab8a6',
    messagingSenderId: '856245188179',
    projectId: 'makeqr-45d3f',
    authDomain: 'makeqr-45d3f.firebaseapp.com',
    storageBucket: 'makeqr-45d3f.appspot.com',
    measurementId: 'G-HBFN8MQC7V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBM8xtrLjlPGUveZ3vYdDpCnvmlyekbKEA',
    appId: '1:856245188179:android:066ab8c43205e11d8ab8a6',
    messagingSenderId: '856245188179',
    projectId: 'makeqr-45d3f',
    storageBucket: 'makeqr-45d3f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD1HdqHDiYg3qVcvoxvv6Cq6TuabG324zY',
    appId: '1:856245188179:ios:1d4a43cdda57ac3b8ab8a6',
    messagingSenderId: '856245188179',
    projectId: 'makeqr-45d3f',
    storageBucket: 'makeqr-45d3f.appspot.com',
    iosBundleId: 'com.example.makeqr',
  );
}
